name: gutenread
description: "A new Flutter project."
publish_to: 'none' #
version: 1.0.0+1

environment:
  sdk: ^3.7.2

isar_version: &isar_version 3.1.8

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.3.1
  freezed_annotation: ^2.4.1
  flutter_riverpod: ^2.5.1
  json_annotation: ^4.9.0
  go_router: ^13.1.0
  dio: ^5.4.1
  flutter_hooks: ^0.20.4
  logger: ^2.0.2+1
  intl: ^0.19.0
  path_provider: ^2.1.2
  connectivity_plus: ^6.0.3
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.2
  isar:
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs:
    version: *isar_version
    hosted: https://pub.isar-community.dev/

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.3
  build_runner: ^2.4.9
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  flutter_lints: ^5.0.0
  isar_generator:
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  path_provider_platform_interface: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: AvenirNext
      fonts:
        - asset: assets/font/AvenirNext-Regular.ttf
        - asset: assets/font/AvenirNext-Bold.otf
          weight: 700
