name: gutenread
description: "A new Flutter project."
publish_to: 'none' #
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  flutter_riverpod: ^2.5.1
  json_annotation: ^4.9.0
  go_router: ^13.1.0
  dio: ^5.4.1
  flutter_hooks: ^0.20.4
  logger: ^2.0.2+1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.3
  build_runner: ^2.4.9
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: AvenirNext
      fonts:
        - asset: assets/font/AvenirNext-Regular.ttf
        - asset: assets/font/AvenirNext-Bold.otf
          weight: 700
